package com.example.domain.models

data class ShowModel(
    val links: LinksModel,
    val averageRuntime: Int,
    val ended: String,
    val externals: ExternalsModel,
    val genres: List<String>,
    val id: Int,
    val image: ImageModel,
    val language: String,
    val name: String,
    val network: NetworkModel,
    val officialSite: String,
    val premiered: String,
    val rating: RatingModel,
    val runtime: Int,
    val schedule: ScheduleModel,
    val status: String,
    val summary: String,
    val type: String,
    val updated: Int,
    val url: String,
    val weight: Int,
) {
    companion object {
        val MOCK = ShowModel(
            links = LinksModel.MOCK,
            averageRuntime = 0,
            ended = "",
            externals = ExternalsModel.MOCK,
            genres = emptyList(),
            id = 0,
            image = ImageModel.MOCK,
            language = "",
            name = "Under the Dome",
            network = NetworkModel.MOCK,
            officialSite = "",
            premiered = "",
            rating = RatingModel.MOCK,
            runtime = 0,
            schedule = ScheduleModel.MOCK,
            status = "",
            summary = "",
            type = "",
            updated = 0,
            url = "",
            weight = 0,
        )
    }
}
